apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-broker-config
  namespace: cloud-course
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: cloud-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: mosquitto-config
          configMap:
            name: mqtt-broker-config
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: cloud-course
  annotations:
    kubernetes.io/elb.class: union
spec:
  type: LoadBalancer
  selector:
    app: mqtt-broker
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-collector
  namespace: cloud-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-collector
  template:
    metadata:
      labels:
        app: mqtt-collector
    spec:
      containers:
        - name: mqtt-collector
          image: swr.cn-east-3.myhuaweicloud.com/cloud-swjtu/mqtt-collector:v1
          imagePullPolicy: Always
          env:
            - name: MQTT_HOST
              value: mqtt-broker.cloud-course.svc.cluster.local
            - name: REDIS_HOST
              value: redis-svc.cloud-course.svc.cluster.local
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
